//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialType
    {
        public string ТипМатериала { get; set; }
        public Nullable<double> ПроцентБракаМатериала { get; set; }
        public int MaterialTypeId { get; set; }
    }
}
