//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProduct
    {
        public string Продукция { get; set; }
        public double КоличествоПродукции { get; set; }
        public System.DateTime ДатаПродажи { get; set; }
        public int IDНаименованияПартнера { get; set; }
        public int PartnerProductsId { get; set; }
    
        public virtual PartnerName PartnerName { get; set; }
    }
}
