//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int IDНаименованиеПартнера { get; set; }
        public string Директор { get; set; }
        public string ЭлектроннаяПочтаПартнера { get; set; }
        public string ТелефонПартнера { get; set; }
        public string ЮридическийАдресПартнера { get; set; }
        public double ИНН { get; set; }
        public double Рейтинг { get; set; }
        public int IDТипаПартнера { get; set; }
        public int PartnersId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual PartnerName PartnerName { get; set; }
        public virtual PartnerType PartnerType { get; set; }
    }
}
